### PR TITLE
Create jeor0980.md

### PR DESCRIPTION
**Pull request by jeor0980**
I'm new.

:100:

### CODE REVIEW

**Comment by mguida22** [comment]
:panda_face: :panda_face: :panda_face:

**Comment by jeor0980** [comment]
no h8 pls

**Comment by mguida22** [comment]
only pandas

**Comment by jeor0980** [comment]
:man:

**Comment by jeor0980** [comment]
where is :taco:?

**Comment by mguida22** [comment]
:tropical_drink:

**Comment by jeor0980** [comment]
:warning:

**Comment by githubteacher** [comment]
:100: :panda_face:

**Pull request merged**
