### PR TITLE
Create 719ben.md - Dancing is cool

### PR DESCRIPTION
**Pull request by biw**
Added dancing.

### CODE REVIEW

**Comment by mguida22** [comment]
:dancers: :shipit:

**Comment by biw** [comment]
gif-keyboard-9006324273951447409

**Comment by mguida22** [comment]
image

**Comment by biw** [comment]
gif-keyboard-17561133749065216550

**Comment by mguida22** [comment]
image

**Comment by biw** [comment]
gif-keyboard-2655730708592253692

**Comment by githubteacher** [comment]
:dancer: :dancer: :dancer:

**Pull request merged**
